# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usrname',
            new_name='username',
        ),
    ]
